-- AlterTable
ALTER TABLE "Report" ADD COLUMN     "brandModel" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "clientSignature" TEXT,
ADD COLUMN     "contactName" TEXT,
ADD COLUMN     "defect" TEXT,
ADD COLUMN     "defectDescription" TEXT,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "forkliftModel" TEXT,
ADD COLUMN     "hourmeter" TEXT,
ADD COLUMN     "loanBrandModel" TEXT,
ADD COLUMN     "loanProvided" BOOLEAN DEFAULT false,
ADD COLUMN     "materialsUsed" JSONB,
ADD COLUMN     "observations" TEXT,
ADD COLUMN     "otherServices" JSONB,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "possibleCauses" TEXT,
ADD COLUMN     "registration" TEXT,
ADD COLUMN     "requestNumber" TEXT,
ADD COLUMN     "result" TEXT,
ADD COLUMN     "serviceDescription" TEXT,
ADD COLUMN     "serviceType" TEXT,
ADD COLUMN     "solution" TEXT,
ADD COLUMN     "technicianSignature" TEXT,
ADD COLUMN     "testPerformed" BOOLEAN,
ADD COLUMN     "testReason" TEXT,
ADD COLUMN     "trips" JSONB,
ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "pdfUrl" DROP NOT NULL;
